# Generated by Django 4.1.1 on 2022-09-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_book_author"),
    ]

    operations = [
        migrations.DeleteModel(name="MyModelName",),
    ]
